### ISSUE TITLE
"Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by ajfoster88** [vipoo/iRacingReplayOverlay.net#69] opened 2015-09-22 23:57 UTC
First off, I want to say that this is a fantastic piece of software. I love that it uses the replay files so well, every other overlay I've found requires live broadcasting.

I've made a number of videos previously without running into this issue. I try to end my videos once everyone has crossed the line. That's usually not a problem. But it was in this instance, it was giving me the error of the title. I looked at the error logs, and I can't quite make heads or tails from them. I've included the last few lines. When I shortened the replay to just after the leader crossed the stripe on the last lap, there was no issue.

INFO: Resetting overtaken2015-09-22T18:38:29	INFO: 01:06:32.9970000 Changing camera to driver: Terry Matthiensen; camera: TV2; within 00:00:01
2015-09-22T18:38:29	INFO: 01:06:32.9970000 Stopping Battle
2015-09-22T18:38:29	INFO: 01:06:32.9970000 Starting Battle
2015-09-22T18:38:30	DEBUG: Failed to read data before iRacing overwrote new sample!
2015-09-22T18:38:30	Warning dropped DataSample from 4887 to 4890. Over time of 0.059
2015-09-22T18:38:31	Warning dropped DataSample from 4934 to 4936. Over time of 0.030
2015-09-22T18:38:32	DEBUG: Received bad sample.  No ReplayFrameNumber.
2015-09-22T18:38:32	INFO: 01:06:43.6670000 Driver Adam Dock has pitted 6 times
2015-09-22T18:38:32	INFO: 01:06:43.6670000 Driver Alex Albert has pitted 6 times
2015-09-22T18:38:32	DEBUG: Received bad sample.  No ReplayFrameNumber.
2015-09-22T18:38:32	INFO: 01:06:43.7970000 Driver Adam Dock has pitted 7 times
2015-09-22T18:38:32	INFO: 01:06:43.7970000 Driver Alex Albert has pitted 7 times
2015-09-22T18:38:32	DEBUG: Received bad sample.  No ReplayFrameNumber.
2015-09-22T18:38:32	INFO: 01:06:44.1970000 Driver Adam Dock has pitted 8 times
2015-09-22T18:38:32	INFO: 01:06:44.1970000 Driver Alex Albert has pitted 8 times
2015-09-22T18:38:33	INFO: 01:06:48.0660000 Changing camera to driver: Terry Matthiensen; camera: TV2
2015-09-22T18:38:33	Warning dropped DataSample from 5053 to 5064. Over time of 0.202
2015-09-22T18:38:34	INFO: 01:06:53.0630000 Found battle Terry Matthiensen by chance 72
INFO: Resetting overtaken2015-09-22T18:38:34	INFO: 01:06:53.0630000 Changing camera to driver: Terry Matthiensen; camera: TV2; within 00:00:01
2015-09-22T18:38:34	INFO: 01:06:53.0630000 Stopping Battle
2015-09-22T18:38:34	INFO: 01:06:53.0630000 Starting Battle
2015-09-22T18:38:34	DEBUG: Failed to read data before iRacing overwrote new sample!
2015-09-22T18:38:34	Warning dropped DataSample from 5140 to 5143. Over time of 0.053
2015-09-22T18:38:38	INFO: 01:07:08.0660000 Changing to forward car, with reverse camera
2015-09-22T18:38:38	INFO: 01:07:08.0660000 Changing camera to driver: Shannon Caudill; camera: Gearbox
2015-09-22T18:38:38	INFO: 01:07:08.3930000 Camera on Shannon Caudill 26 in position 1st
2015-09-22T18:38:38	DEBUG: Failed to read data before iRacing overwrote new sample!
2015-09-22T18:38:38	Warning dropped DataSample from 5357 to 5360. Over time of 0.050
2015-09-22T18:38:39

**Comment by vipoo** [comment] 2015-12-29 00:38
Hi,

Was just reviewing the issue list, and saw this issue you raised long time ago.  Sorry about that.

Is this a problem for you?

Not sure what version, you were using back then, but there have been a few updates - with more coming soon.

Please advise if u are happy or not, for me to close this issue?

Dean

**Comment by ajfoster88** [comment] 2015-12-29 00:45
Wow. I'd forgotten about it as well. I've updated a time or two since then and I haven't seen the error again. It happened on an IndyCar oval race and I've only been doing road races for a bit and haven't seen it again, so it's probably fine?

**Comment by LaundroMat** [comment] 2016-03-04 18:15
I have the same issue: 

![capture](https://cloud.githubusercontent.com/assets/42320/13535976/6a6e175e-e23d-11e5-9ffb-37419c68d4e0.PNG)

It happens at every interaction: when starting the application and any button I click.

Version: 1.0.0.26 on Windows 10.

**Comment by vipoo** [comment] 2016-03-05 01:20
Hi,

I am not sure what the cause of your issue is.  Can i please request you try the latest version of the application, and see if the problem persists.

If it does, please send me your TrackingId or log files, to help me diagnose the issue.

See http://members.iracing.com/jforum/posts/list/3271807.page#8336745 for details on new release model.

Please try version 1.0.3.34

Cheers
Dean

**Comment by LaundroMat** [comment] 2016-03-05 08:26
Hi Dean,

I have removed and reinstalled the application and all is fine and dandy again. You can close the ticket again, sorry.

Keep up the great work!

**Closed** 2016-03-05 10:26 UTC
